spring:
  application:
    name: EventClean

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5436/eventClean
    username: postgres
    password: postgres

  jpa:
    show-sql: true

  flyway:
    enabled: true
    locations:
      - classpath:db/migration
